# Generated by Django 2.1.2 on 2019-11-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerStyle', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=10)),
                ('target', models.CharField(max_length=10)),
                ('data', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
            ],
        ),
    ]
